"""Parse SRT subtitles into CLPZ transcript format.

If a ``words.json`` file exists alongside the SRT, precise word timestamps
from the transcription engine are used.  Otherwise, approximate per-word
timestamps are generated by splitting each subtitle's duration evenly.
"""
from __future__ import annotations

import json
import re
from pathlib import Path


def _timestamp_to_seconds(timestamp: str) -> float:
    """Convert SRT timestamp HH:MM:SS,mmm into seconds."""
    timestamp = timestamp.strip().replace(",", ".")

    parts = timestamp.split(":")
    if len(parts) != 3:
        raise ValueError(f"Invalid SRT timestamp: {timestamp}")

    hours = float(parts[0])
    minutes = float(parts[1])
    seconds = float(parts[2])

    return hours * 3600 + minutes * 60 + seconds


def _segment_words(start: float, end: float, dialogue: str) -> list[dict]:
    """Split one subtitle's text into approximate per-word timestamps.

    SRT only has line-level timestamps, so each word gets an even slice of
    the subtitle's duration.  Deterministic and simple: no NLP, no alignment.
    Tokens without any alphanumeric character ("♪", "—") are dropped.
    """
    tokens = [
        t for t in re.split(r"\s+", dialogue) if t
        and re.search(r"[A-Za-z0-9]", t)
    ]

    if not tokens:
        return []

    step = (end - start) / len(tokens)

    return [
        {
            "start": round(start + i * step, 3),
            "end": round(start + (i + 1) * step, 3),
            "word": token,
        }
        for i, token in enumerate(tokens)
    ]


def _load_words_json(srt_path: Path) -> list[dict] | None:
    """Try to load precise word timestamps from words.json next to the SRT.

    Returns the word list if the file exists and is valid, else None.
    """
    words_file = srt_path.parent / "words.json"
    if not words_file.exists():
        return None
    try:
        data = json.loads(words_file.read_text(encoding="utf-8"))
        if isinstance(data, list) and data:
            # Validate structure: each entry must have start, end, word
            sample = data[0]
            if all(k in sample for k in ("start", "end", "word")):
                return data
    except (json.JSONDecodeError, OSError, KeyError):
        pass
    return None


def parse_srt(path: str) -> dict:
    """
    Convert an SRT file into the transcript structure CLPZ uses.

    If a ``words.json`` file exists in the same directory, precise word
    timestamps from the transcription engine are used.  Otherwise, each
    subtitle's duration is split evenly across its words.

    Returns:
        {
            "language": "unknown",
            "segments": [
                {"start": 1.2, "end": 4.5, "text": "..."}
            ],
            "words": [
                {"start": 1.2, "end": 2.1, "word": "..."}
            ]
        }
    """
    srt_path = Path(path)

    # Try to load precise word timestamps from words.json
    precise_words = _load_words_json(srt_path)

    with open(srt_path, "r", encoding="utf-8-sig") as f:
        text = f.read()

    # Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n").strip()

    if not text:
        raise ValueError("The SRT file is empty.")

    blocks = re.split(r"\n\s*\n", text)

    segments = []
    words = []

    for block in blocks:
        lines = [line.strip() for line in block.split("\n") if line.strip()]

        if len(lines) < 2:
            continue

        # Find the timestamp line instead of assuming it is always line 2.
        time_index = None

        for i, line in enumerate(lines):
            if "-->" in line:
                time_index = i
                break

        if time_index is None:
            continue

        time_line = lines[time_index]

        try:
            start_text, end_text = re.split(r"\s*-->\s*", time_line, maxsplit=1)

            # Remove optional SRT positioning information after end timestamp.
            end_text = end_text.split()[0]

            start = _timestamp_to_seconds(start_text)
            end = _timestamp_to_seconds(end_text)
        except Exception:
            continue

        # Everything after the timestamp is subtitle dialogue.
        dialogue = " ".join(lines[time_index + 1:])

        # Remove common HTML subtitle tags.
        dialogue = re.sub(r"<[^>]+>", "", dialogue)

        # Decode common escaped characters.
        dialogue = (
            dialogue
            .replace("&amp;", "&")
            .replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&quot;", '"')
            .replace("&#39;", "'")
        )

        dialogue = re.sub(r"\s+", " ", dialogue).strip()

        if not dialogue:
            continue

        if end <= start:
            continue

        segments.append({
            "start": round(start, 3),
            "end": round(end, 3),
            "text": dialogue,
        })

        words.extend(_segment_words(start, end, dialogue))

    if not segments:
        raise ValueError(
            "No valid subtitles were found in the SRT file."
        )

    segments.sort(key=lambda s: s["start"])

    # Use precise word timestamps if available
    if precise_words is not None:
        words = precise_words

    return {
        "language": "unknown",
        "segments": segments,
        "words": words,
    }