/**
 * Vercel build script: injects environment variables into frontend/config.js
 *
 * Vercel environment variables to set (Settings → Environment Variables):
 *   NEXT_PUBLIC_SUPABASE_URL    →  https://xxxxx.supabase.co
 *   NEXT_PUBLIC_SUPABASE_ANON_KEY →  eyJhbGci...
 *
 * For local dev, create frontend/config.js manually with your values.
 */
const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('⚠️  NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY not set.');
  console.warn('   Auth will not work without these. Set them in Vercel dashboard → Settings → Environment Variables.');
}

const configContent = `// Auto-generated by build script. Do not edit manually.
// Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in Vercel.
window.__CLPZ_SUPABASE_URL__ = ${JSON.stringify(supabaseUrl)};
window.__CLPZ_SUPABASE_ANON_KEY__ = ${JSON.stringify(supabaseAnonKey)};
`;

const configPath = path.join(__dirname, '..', 'frontend', 'config.js');
fs.writeFileSync(configPath, configContent, 'utf-8');
console.log('✅ frontend/config.js generated with Supabase credentials.');
