// Run with the bundled Node runtime; pass PLAYWRIGHT_MODULE when it is not on NODE_PATH.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const assert = require('node:assert/strict');
const output = path.resolve('docs/ui-checks');
fs.mkdirSync(output, { recursive: true });
const job = {id:'ui-fixture',stage:'done',created_at:1788960000,input_type:'upload',video:{title:'A little perspective'},clips:[{index:0,title:'The moment it clicked',status:'done',duration:15,start:5,end:20,stream_url:'/fixture.mp4',download_url:'/fixture.mp4',caption_words:[{word:'Keep'},{word:'creating.'}],validation:{width:1080,height:1920,video_codec:'h264',audio_codec:'aac'}}]};
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(fs.readFileSync('frontend/clpz.html'));});
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  try {
    const page=await browser.newPage({viewport:{width:1440,height:1000}});
    const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR:',e.message);});
    await page.goto(process.env.SITE_URL||'http://127.0.0.1:43187');
    await page.screenshot({path:path.join(output,'website-light.png'),fullPage:true});
    await page.getByRole('button',{name:'Switch to dark mode'}).click();
    await page.screenshot({path:path.join(output,'website-dark.png'),fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.classList.contains('dark')),true);
    await page.getByRole('button',{name:'Switch to light mode'}).click();
    await page.setViewportSize({width:390,height:844});
    await page.reload();
    await page.getByRole('button',{name:'Open navigation'}).click();
    await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link',{name:'Get the app'}).click();
    await page.waitForURL('**/apps');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile download page overflows');
    await page.screenshot({path:path.join(output,'website-mobile-apps.png'),fullPage:true});
    await page.goto((process.env.SITE_URL||'http://127.0.0.1:43187')+'/login');
    await page.getByLabel('Password',{exact:true}).fill('test-only');
    await page.getByRole('button',{name:'Show password'}).click();
    assert.equal(await page.getByLabel('Password',{exact:true}).getAttribute('type'),'text');
    await page.getByRole('button',{name:'Create account',exact:true}).click();
    await page.getByLabel('Confirm password').fill('different');
    await page.screenshot({path:path.join(output,'website-mobile-auth.png'),fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile auth overflows');
    await page.route('**/api/**',route=>{const url=route.request().url();const data=url.endsWith('/api/jobs')?[job]:url.includes('diagnostics')?{ffmpeg:'found',ffprobe:'found',whisper:'available',editor:'available'}:url.includes('credits')?{balance:0,cost_per_forge:1}:{};return route.fulfill({json:data});});
    await page.setViewportSize({width:1440,height:1000});
    await page.goto('http://127.0.0.1:'+server.address().port+'/?desktop=1');
    await page.locator('#dash-projects .project').waitFor();
    await page.screenshot({path:path.join(output,'desktop-studio.png'),fullPage:true});
    await page.locator('#dash-clips .edit').click();
    await page.locator('[data-tool=text]').click();
    await page.locator('#text-input').fill('Make it count.');
    await page.locator('#text-add').click();
    await page.waitForTimeout(350);
    await page.locator('#close-editor').click();
    await page.locator('#clip-grid .edit').click();
    await page.locator('[data-tool=text]').click();
    await page.locator('#text-list').getByText('Make it count.').waitFor();
    await page.screenshot({path:path.join(output,'desktop-editor.png'),fullPage:true});
    await page.locator('#text-input').fill('Another line');
    await page.locator('#text-add').click();
    await page.locator('#editor-undo').click();
    assert.equal(await page.locator('#text-list').getByText('Another line').count(),0);
    await page.locator('#editor-redo').click();
    await page.locator('#text-list').getByText('Another line').waitFor();
    await page.locator('#close-editor').click();
    await page.locator('.nav [data-nav=projects]').click();
    await page.locator('#project-grid .project').waitFor();
    await page.locator('#project-search').fill('missing search');
    assert.equal(await page.locator('#project-grid .project:visible').count(),0);
    await page.locator('#project-search').fill('perspective');
    assert.equal(await page.locator('#project-grid .project:visible').count(),1);
    assert.deepEqual(errors,[],'Client-side errors');
    console.log('PASS: mobile navigation, password visibility, responsive layout, desktop draft persistence, undo/redo, project search. Desktop API uses a test fixture; no real processing or payments tested.');
  } finally {await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
